services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod

  db_backup:
    build:
      context: ./db_backup
      dockerfile: Dockerfile
