services:
  frontend:
    image: haeuserbuch_frontend
    env_file:
      - .env
    container_name: frontend
    build:
      context: ./haeuserbuch_frontend
    depends_on:
      - backend
    networks:
      - haeuserbuch_network
    restart: unless-stopped

  backend:
    image: haeuserbuch_backend
    container_name: backend
    build:
      context: ./haeuserbuch_backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - ${WORKSPACE:?error}/uploads:/uploads
    depends_on:
      database:
        condition: service_healthy
    networks:
      - haeuserbuch_network
    restart: unless-stopped

  database:
    image: postgis/postgis:17-3.5-alpine
    container_name: haeuserbuch_db
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      # In case you have a database dump, uncomment the following line and change the file name
      # - ./<your_dump>.sql:/docker-entrypoint-initdb.d/<your_dump>.sql
      - ${WORKSPACE:?error}/db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}" ]
      interval: 30s
      retries: 10
      start_period: 60s
    networks:
      - haeuserbuch_network
    restart: unless-stopped

  db_backup:
    image: postgres:17-alpine
    container_name: db_backup
    environment:
      - PGPASSWORD=${DB_PASSWORD}
    volumes:
      - ${BACKUPS:?error}/db_backups:/backups
    entrypoint: /bin/sh
    command: -c "sleep 90; while true; do
      pg_dump -h haeuserbuch_db -U ${DB_USER} ${DB_NAME} | gzip > /backups/haeuserbuch_$(date +'%Y%m%d_%H%M%S').sql.gz;
      find /backups -type f -name '*.sql.gz' -mtime +7 -delete;
      sleep 86400;
      done"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - haeuserbuch_network
    restart: unless-stopped

  nginx:
    image: nginx:alpine-slim
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "${GENERAL_PORT:-80}:80"
    depends_on:
      - frontend
      - backend
    networks:
      - haeuserbuch_network
    restart: unless-stopped

  tileserver:
    image: maptiler/tileserver-gl:v5.4.0
    container_name: tileserver
    volumes:
      - ${TILES:?error}:/data
    networks:
      - haeuserbuch_network
    command: --public_url /tiles/
    restart: unless-stopped

networks:
  haeuserbuch_network:
    driver: bridge
