-- Baseline schema for a new Häuserbuch database.
-- Existing restored databases are recorded at baseline version 1 and skip this migration.

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'postgis') THEN
        RAISE EXCEPTION 'PostGIS must be installed before Flyway creates the application schema';
    END IF;
END
$$;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: address; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.address (
    id bigint NOT NULL,
    created_by character varying(255),
    created_date timestamp(6) without time zone,
    general_notes text,
    internal_notes text,
    last_modified_by character varying(255),
    last_modified_date timestamp(6) without time zone,
    from_date character varying(255),
    house_number character varying(255),
    to_date character varying(255),
    street_id bigint,
    building_id bigint
);


--
-- Name: address_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.address ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.address_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: building; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.building (
    id bigint NOT NULL,
    created_by character varying(255),
    created_date timestamp(6) without time zone,
    general_notes text,
    internal_notes text,
    last_modified_by character varying(255),
    last_modified_date timestamp(6) without time zone,
    coordinates public.geometry(Geometry,4326),
    district_property_number character varying(255),
    property_number character varying(255),
    parcel_number bigint,
    parcel_number_counter bigint,
    part_type character varying(255),
    object character varying(255),
    year bigint,
    district_id bigint,
    quarter_id bigint
);


--
-- Name: building_alt_names; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.building_alt_names (
    building_id bigint NOT NULL,
    alt_names character varying(255)
);


--
-- Name: building_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.building ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.building_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: building_literature; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.building_literature (
    building_id bigint NOT NULL,
    source_id bigint NOT NULL,
    secondary_sources character varying(255)
);


--
-- Name: building_name; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.building_name (
    id bigint NOT NULL,
    created_by character varying(255),
    created_date timestamp(6) without time zone,
    general_notes text,
    internal_notes text,
    last_modified_by character varying(255),
    last_modified_date timestamp(6) without time zone,
    from_date character varying(255),
    name character varying(255),
    to_date character varying(255),
    source_id bigint,
    building_id bigint
);


--
-- Name: building_name_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.building_name ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.building_name_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: building_source; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.building_source (
    building_id bigint NOT NULL,
    source_id bigint NOT NULL
);


--
-- Name: citizenship; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.citizenship (
    id bigint NOT NULL,
    created_by character varying(255),
    created_date timestamp(6) without time zone,
    general_notes text,
    internal_notes text,
    last_modified_by character varying(255),
    last_modified_date timestamp(6) without time zone,
    addendum character varying(255),
    date_misc character varying(255),
    date_naturalization character varying(255),
    entry_text text,
    ref_number character varying(255),
    signature character varying(255),
    person_id bigint,
    primary_source_id bigint,
    secondary_source_id bigint,
    full_text_vector tsvector GENERATED ALWAYS AS (to_tsvector('german'::regconfig, entry_text)) STORED
);


--
-- Name: citizenship_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.citizenship ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.citizenship_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: citizenship_mentioned_person; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.citizenship_mentioned_person (
    citizenship_id bigint NOT NULL,
    person_id bigint NOT NULL
);


--
-- Name: district; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.district (
    id bigint NOT NULL,
    created_by character varying(255),
    created_date timestamp(6) without time zone,
    general_notes text,
    internal_notes text,
    last_modified_by character varying(255),
    last_modified_date timestamp(6) without time zone,
    description character varying(255),
    name character varying(255)
);


--
-- Name: district_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.district ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.district_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: job; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.job (
    id bigint NOT NULL,
    created_by character varying(255),
    created_date timestamp(6) without time zone,
    general_notes text,
    internal_notes text,
    last_modified_by character varying(255),
    last_modified_date timestamp(6) without time zone,
    description character varying(255),
    name character varying(255)
);


--
-- Name: origin_places; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.origin_places (
    person_id bigint NOT NULL,
    place_id bigint NOT NULL
);


--
-- Name: person; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.person (
    id bigint NOT NULL,
    created_by character varying(255),
    created_date timestamp(6) without time zone,
    general_notes text,
    internal_notes text,
    last_modified_by character varying(255),
    last_modified_date timestamp(6) without time zone,
    first_name character varying(255),
    full_name character varying(255),
    is_citizen boolean,
    job_original_text character varying(255),
    last_name character varying(255),
    origin_certainty character varying(255),
    origin_original_text character varying(255),
    religion_original_text character varying(255),
    sex character varying(255),
    building_id bigint,
    job_category_id bigint,
    religion_category_id bigint,
    CONSTRAINT person_origin_certainty_check CHECK (((origin_certainty)::text = ANY (ARRAY[('IDENTIFIED'::character varying)::text, ('AMBIGUOUS'::character varying)::text, ('UNKNOWN'::character varying)::text])))
);


--
-- Name: person_alt_names; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.person_alt_names (
    person_id bigint NOT NULL,
    alt_names character varying(255)
);


--
-- Name: place; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.place (
    id bigint NOT NULL,
    created_by character varying(255),
    created_date timestamp(6) without time zone,
    general_notes text,
    internal_notes text,
    last_modified_by character varying(255),
    last_modified_date timestamp(6) without time zone,
    coordinates public.geometry(Geometry,4326),
    is_uncertain boolean,
    real_name character varying(255)
);


--
-- Name: place_alt_names; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.place_alt_names (
    place_id bigint NOT NULL,
    alt_names character varying(255)
);


--
-- Name: quarter; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.quarter (
    id bigint NOT NULL,
    created_by character varying(255),
    created_date timestamp(6) without time zone,
    general_notes text,
    internal_notes text,
    last_modified_by character varying(255),
    last_modified_date timestamp(6) without time zone,
    description character varying(255),
    name character varying(255)
);


--
-- Name: religion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.religion (
    id bigint NOT NULL,
    created_by character varying(255),
    created_date timestamp(6) without time zone,
    general_notes text,
    internal_notes text,
    last_modified_by character varying(255),
    last_modified_date timestamp(6) without time zone,
    description character varying(255),
    name character varying(255)
);


--
-- Name: source; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.source (
    id bigint NOT NULL,
    created_by character varying(255),
    created_date timestamp(6) without time zone,
    general_notes text,
    internal_notes text,
    last_modified_by character varying(255),
    last_modified_date timestamp(6) without time zone,
    description character varying(255),
    signature character varying(255),
    title character varying(255),
    type character varying(255)
);


--
-- Name: source_authors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.source_authors (
    source_id bigint NOT NULL,
    authors character varying(255)
);


--
-- Name: street; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.street (
    id bigint NOT NULL,
    created_by character varying(255),
    created_date timestamp(6) without time zone,
    general_notes text,
    internal_notes text,
    last_modified_by character varying(255),
    last_modified_date timestamp(6) without time zone,
    description character varying(255),
    name character varying(255)
);


--
-- Name: street_alt_names; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.street_alt_names (
    street_id bigint NOT NULL,
    alt_names character varying(255)
);


--
-- Name: weapon; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.weapon (
    id bigint NOT NULL,
    created_by character varying(255),
    created_date timestamp(6) without time zone,
    general_notes text,
    internal_notes text,
    last_modified_by character varying(255),
    last_modified_date timestamp(6) without time zone,
    description character varying(255),
    name character varying(255)
);


--
-- Name: weaponry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.weaponry (
    id bigint NOT NULL,
    created_by character varying(255),
    created_date timestamp(6) without time zone,
    general_notes text,
    internal_notes text,
    last_modified_by character varying(255),
    last_modified_date timestamp(6) without time zone,
    original_text character varying(255),
    weapon_id bigint,
    person_id bigint
);


--
-- Name: job_alt_names; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.job_alt_names (
    job_id bigint NOT NULL,
    alt_names character varying(255)
);


--
-- Name: occupation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.job ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.occupation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ownership; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ownership (
    id bigint NOT NULL,
    created_by character varying(255),
    created_date timestamp(6) without time zone,
    general_notes text,
    internal_notes text,
    last_modified_by character varying(255),
    last_modified_date timestamp(6) without time zone,
    date character varying(255),
    entry_text text,
    price bigint,
    type character varying(255),
    owner_id bigint NOT NULL,
    seller_id bigint NOT NULL,
    source_id bigint NOT NULL
);


--
-- Name: ownership_building; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ownership_building (
    ownership_id bigint NOT NULL,
    building_id bigint NOT NULL
);


--
-- Name: ownership_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ownership ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ownership_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: person_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.person ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.person_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: place_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.place ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.place_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: quarter_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.quarter ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quarter_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: religion_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.religion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.religion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: source_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.source ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.source_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: source_links; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.source_links (
    source_id bigint NOT NULL,
    links character varying(255)
);


--
-- Name: street_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.street ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.street_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tax; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tax (
    id bigint NOT NULL,
    created_by character varying(255),
    created_date timestamp(6) without time zone,
    general_notes text,
    internal_notes text,
    last_modified_by character varying(255),
    last_modified_date timestamp(6) without time zone,
    entry_text character varying(255),
    plan_number character varying(255),
    tax_number character varying(255),
    building_id bigint NOT NULL,
    person_id bigint,
    source_id bigint NOT NULL
);


--
-- Name: tax_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tax ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tax_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: weapon_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.weapon ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.weapon_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: weaponry_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.weaponry ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.weaponry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: address address_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.address
    ADD CONSTRAINT address_pkey PRIMARY KEY (id);


--
-- Name: building_name building_name_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.building_name
    ADD CONSTRAINT building_name_pkey PRIMARY KEY (id);


--
-- Name: building building_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.building
    ADD CONSTRAINT building_pkey PRIMARY KEY (id);


--
-- Name: building_source building_primary_source_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.building_source
    ADD CONSTRAINT building_primary_source_pkey PRIMARY KEY (building_id, source_id);


--
-- Name: building_literature building_secondary_source_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.building_literature
    ADD CONSTRAINT building_secondary_source_pkey PRIMARY KEY (building_id, source_id);


--
-- Name: citizenship_mentioned_person citizenship_mentioned_person_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.citizenship_mentioned_person
    ADD CONSTRAINT citizenship_mentioned_person_pkey PRIMARY KEY (citizenship_id, person_id);


--
-- Name: citizenship citizenship_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.citizenship
    ADD CONSTRAINT citizenship_pkey PRIMARY KEY (id);


--
-- Name: district district_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.district
    ADD CONSTRAINT district_pkey PRIMARY KEY (id);


--
-- Name: job occupation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job
    ADD CONSTRAINT occupation_pkey PRIMARY KEY (id);


--
-- Name: ownership_building ownership_building_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ownership_building
    ADD CONSTRAINT ownership_building_pkey PRIMARY KEY (ownership_id, building_id);


--
-- Name: ownership ownership_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ownership
    ADD CONSTRAINT ownership_pkey PRIMARY KEY (id);


--
-- Name: person person_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.person
    ADD CONSTRAINT person_pkey PRIMARY KEY (id);


--
-- Name: place place_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.place
    ADD CONSTRAINT place_pkey PRIMARY KEY (id);


--
-- Name: quarter quarter_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quarter
    ADD CONSTRAINT quarter_pkey PRIMARY KEY (id);


--
-- Name: religion religion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.religion
    ADD CONSTRAINT religion_pkey PRIMARY KEY (id);


--
-- Name: source source_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.source
    ADD CONSTRAINT source_pkey PRIMARY KEY (id);


--
-- Name: street street_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.street
    ADD CONSTRAINT street_pkey PRIMARY KEY (id);


--
-- Name: tax tax_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tax
    ADD CONSTRAINT tax_pkey PRIMARY KEY (id);


--
-- Name: weapon weapon_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.weapon
    ADD CONSTRAINT weapon_pkey PRIMARY KEY (id);


--
-- Name: weaponry weaponry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.weaponry
    ADD CONSTRAINT weaponry_pkey PRIMARY KEY (id);


--
-- Name: idx_full_text_vector_gin; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_full_text_vector_gin ON public.citizenship USING gin (full_text_vector);


--
-- Name: tax fk19v7q0aluwnjj6mh31o495092; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tax
    ADD CONSTRAINT fk19v7q0aluwnjj6mh31o495092 FOREIGN KEY (person_id) REFERENCES public.person(id);


--
-- Name: building_name fk2jse5tn6gkkk927velahaegvt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.building_name
    ADD CONSTRAINT fk2jse5tn6gkkk927velahaegvt FOREIGN KEY (source_id) REFERENCES public.source(id);


--
-- Name: person_alt_names fk2oern52mfo165yot53h04xtw3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.person_alt_names
    ADD CONSTRAINT fk2oern52mfo165yot53h04xtw3 FOREIGN KEY (person_id) REFERENCES public.person(id);


--
-- Name: job_alt_names fk4ntbnudwyuc1gt9m6stbe57f7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job_alt_names
    ADD CONSTRAINT fk4ntbnudwyuc1gt9m6stbe57f7 FOREIGN KEY (job_id) REFERENCES public.job(id);


--
-- Name: origin_places fk5i07uha1l4mmgnytxo4xj3y78; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.origin_places
    ADD CONSTRAINT fk5i07uha1l4mmgnytxo4xj3y78 FOREIGN KEY (place_id) REFERENCES public.place(id);


--
-- Name: citizenship fk5t837cyaxycgovap9kd74pxew; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.citizenship
    ADD CONSTRAINT fk5t837cyaxycgovap9kd74pxew FOREIGN KEY (secondary_source_id) REFERENCES public.source(id);


--
-- Name: street_alt_names fk5xb13tr0it25in7ogov93v7ix; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.street_alt_names
    ADD CONSTRAINT fk5xb13tr0it25in7ogov93v7ix FOREIGN KEY (street_id) REFERENCES public.street(id);


--
-- Name: weaponry fk6lbsbfnov27jpg643p4692nnk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.weaponry
    ADD CONSTRAINT fk6lbsbfnov27jpg643p4692nnk FOREIGN KEY (person_id) REFERENCES public.person(id);


--
-- Name: tax fk6qxj3pu1eevfispbtkvp1gyer; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tax
    ADD CONSTRAINT fk6qxj3pu1eevfispbtkvp1gyer FOREIGN KEY (source_id) REFERENCES public.source(id);


--
-- Name: person fk6w6dv1a01g3m7sa5fhvn9ri8i; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.person
    ADD CONSTRAINT fk6w6dv1a01g3m7sa5fhvn9ri8i FOREIGN KEY (religion_category_id) REFERENCES public.religion(id);


--
-- Name: citizenship_mentioned_person fk7hgdrfxx6h8ld9f1qjiud919g; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.citizenship_mentioned_person
    ADD CONSTRAINT fk7hgdrfxx6h8ld9f1qjiud919g FOREIGN KEY (person_id) REFERENCES public.person(id);


--
-- Name: building fk8lsralwnmpmlb745ek0gf3v00; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.building
    ADD CONSTRAINT fk8lsralwnmpmlb745ek0gf3v00 FOREIGN KEY (district_id) REFERENCES public.district(id);


--
-- Name: building fk8r32b5ucmmv0u2vcq4ew0m16g; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.building
    ADD CONSTRAINT fk8r32b5ucmmv0u2vcq4ew0m16g FOREIGN KEY (quarter_id) REFERENCES public.quarter(id);


--
-- Name: place_alt_names fk95yilb6qnqymuee7m0is3vp1j; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.place_alt_names
    ADD CONSTRAINT fk95yilb6qnqymuee7m0is3vp1j FOREIGN KEY (place_id) REFERENCES public.place(id);


--
-- Name: address fk9fe4jtcvri4a7ycxf4w4mb5js; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.address
    ADD CONSTRAINT fk9fe4jtcvri4a7ycxf4w4mb5js FOREIGN KEY (building_id) REFERENCES public.building(id);


--
-- Name: building_name fk9ikmgkufv8tncqmre09e7tv1r; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.building_name
    ADD CONSTRAINT fk9ikmgkufv8tncqmre09e7tv1r FOREIGN KEY (building_id) REFERENCES public.building(id);


--
-- Name: citizenship fka201dtdaqll5cmj4lovgg2pf6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.citizenship
    ADD CONSTRAINT fka201dtdaqll5cmj4lovgg2pf6 FOREIGN KEY (primary_source_id) REFERENCES public.source(id);


--
-- Name: source_links fka6kurj19ig6n6it6kg91c8olb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.source_links
    ADD CONSTRAINT fka6kurj19ig6n6it6kg91c8olb FOREIGN KEY (source_id) REFERENCES public.source(id);


--
-- Name: ownership_building fkctbkq9g1rqodps64anfcm9h1n; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ownership_building
    ADD CONSTRAINT fkctbkq9g1rqodps64anfcm9h1n FOREIGN KEY (building_id) REFERENCES public.building(id);


--
-- Name: tax fkcwxlftpfqkrmtrj5os9fjd29v; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tax
    ADD CONSTRAINT fkcwxlftpfqkrmtrj5os9fjd29v FOREIGN KEY (building_id) REFERENCES public.building(id);


--
-- Name: weaponry fke4ncb9dirylwdi3dj55csd4k5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.weaponry
    ADD CONSTRAINT fke4ncb9dirylwdi3dj55csd4k5 FOREIGN KEY (weapon_id) REFERENCES public.weapon(id);


--
-- Name: ownership_building fkfhgxq24ekarrrxwrbxu62plwy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ownership_building
    ADD CONSTRAINT fkfhgxq24ekarrrxwrbxu62plwy FOREIGN KEY (ownership_id) REFERENCES public.ownership(id);


--
-- Name: address fkft0pt0eni21ptl8s37dtq8s9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.address
    ADD CONSTRAINT fkft0pt0eni21ptl8s37dtq8s9 FOREIGN KEY (street_id) REFERENCES public.street(id);


--
-- Name: building_source fkg25wp8k8r9omdxxur6ki7mo1k; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.building_source
    ADD CONSTRAINT fkg25wp8k8r9omdxxur6ki7mo1k FOREIGN KEY (source_id) REFERENCES public.source(id);


--
-- Name: building_source fkl3h2ypsh7awsuu8i0f31t07mp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.building_source
    ADD CONSTRAINT fkl3h2ypsh7awsuu8i0f31t07mp FOREIGN KEY (building_id) REFERENCES public.building(id);


--
-- Name: ownership fkm2n8olicqs9h4fjkwukfm98om; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ownership
    ADD CONSTRAINT fkm2n8olicqs9h4fjkwukfm98om FOREIGN KEY (owner_id) REFERENCES public.person(id);


--
-- Name: ownership fkma8jlcs53hb3aarunw5gemlta; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ownership
    ADD CONSTRAINT fkma8jlcs53hb3aarunw5gemlta FOREIGN KEY (source_id) REFERENCES public.source(id);


--
-- Name: building_literature fknlgbpgk7qfarulei08gsuao7s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.building_literature
    ADD CONSTRAINT fknlgbpgk7qfarulei08gsuao7s FOREIGN KEY (building_id) REFERENCES public.building(id);


--
-- Name: citizenship_mentioned_person fkppd2ht5q9dknt1lmwai7st79y; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.citizenship_mentioned_person
    ADD CONSTRAINT fkppd2ht5q9dknt1lmwai7st79y FOREIGN KEY (citizenship_id) REFERENCES public.citizenship(id);


--
-- Name: origin_places fkq7w6gnj06nc01yeigfnf5ig8l; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.origin_places
    ADD CONSTRAINT fkq7w6gnj06nc01yeigfnf5ig8l FOREIGN KEY (person_id) REFERENCES public.person(id);


--
-- Name: source_authors fkqto5lqc9kbuke6j54qbbqyop7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.source_authors
    ADD CONSTRAINT fkqto5lqc9kbuke6j54qbbqyop7 FOREIGN KEY (source_id) REFERENCES public.source(id);


--
-- Name: ownership fkroiu1yru8y4u2i4ghyyj1cjpo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ownership
    ADD CONSTRAINT fkroiu1yru8y4u2i4ghyyj1cjpo FOREIGN KEY (seller_id) REFERENCES public.person(id);


--
-- Name: citizenship fksiwvhsqkpiskrcyi5iyf05f2g; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.citizenship
    ADD CONSTRAINT fksiwvhsqkpiskrcyi5iyf05f2g FOREIGN KEY (person_id) REFERENCES public.person(id);


--
-- Name: building_literature fksk5w6j1lh1jexese8xfgl3qfs; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.building_literature
    ADD CONSTRAINT fksk5w6j1lh1jexese8xfgl3qfs FOREIGN KEY (source_id) REFERENCES public.source(id);


--
-- Name: person fkt6lh2rinii15xf4rcimyva341; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.person
    ADD CONSTRAINT fkt6lh2rinii15xf4rcimyva341 FOREIGN KEY (job_category_id) REFERENCES public.job(id);


--
-- Name: person fktlh0fohmywfusq43rhq20lvp3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.person
    ADD CONSTRAINT fktlh0fohmywfusq43rhq20lvp3 FOREIGN KEY (building_id) REFERENCES public.building(id);


--
-- PostgreSQL database dump complete
--
