CREATE TABLE public.file (
    id bigint NOT NULL,
    created_by character varying(255),
    created_date timestamp(6) without time zone,
    general_notes text,
    internal_notes text,
    last_modified_by character varying(255),
    last_modified_date timestamp(6) without time zone,
    name character varying(255),
    original_name character varying(255),
    path character varying(255),
    size bigint,
    type character varying(255)
);

ALTER TABLE public.file ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.file_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.building_file (
    building_id bigint NOT NULL,
    file_id bigint NOT NULL
);

ALTER TABLE ONLY public.file
    ADD CONSTRAINT file_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.building_file
    ADD CONSTRAINT building_file_pkey PRIMARY KEY (building_id, file_id);

ALTER TABLE ONLY public.building_file
    ADD CONSTRAINT fkb9b0h8u147yrheipw7gq2abw9
    FOREIGN KEY (building_id) REFERENCES public.building(id);

ALTER TABLE ONLY public.building_file
    ADD CONSTRAINT fkp60iimhbmrmgua2oq0fcwqcsm
    FOREIGN KEY (file_id) REFERENCES public.file(id);
