CREATE TABLE public.ownerhsip_record
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(255),
    internal_notes     TEXT,
    general_notes      TEXT,
    CONSTRAINT pk_ownerhsip_record PRIMARY KEY (id)
);
