# Create the application.yml file with the following content
# and fill out the placeholders with your secrets

spring:
  application:
    name: haeuserbuch_backend

  datasource:
    url: # database URL
    username: # database username
    password: # database password

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 500MB

  config:
    files:
      upload-dir: /files

server:
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024
